# -*- coding: utf8 -*-

ids = [
##my-epg
"HBO",
"HBO 2",
"HBO 3",
"Cinemax",
"Cinemax 2",
#Sport EPG
"Sport1 US",
"Sport1+",
"Viasat Sport",
"Sport Klub 1",
"Sport Klub 2",
"Sport Klub 3",
"Sport Klub 4",
"Sport Klub 5",
"Sport Klub 6",
"Sport Klub 1 HR",
"Sport Klub 2 HR",
"Sport Klub 3 HR",
"Arena Sport 1 (SRB)",
"Arena Sport 2 (SRB)",
"Arena Sport 3 (SRB)",
"Arena Sport 4 (SRB)",
"Arena Sport 5 (SRB)",
"Arena Sport 1 HR",
"Arena Sport 2 HR",
"Arena Sport 3 HR",
"Arena Sport 4 HR",
"Arena Sport 5 HR",
"Sky Sports 1",
"Sky Sports 2",
"Sky Sports 3",
"Sky Sports 4",
"Sky Sports 5",
"Sky Sports F1",
"FOX Sports 1 NL",
"FOX Sports 2 NL",
"FOX Sports 3 NL",
"FOX Sports 4 NL",
"FOX Sports 5 NL",
"FOX Sports 6 NL",
"BT Sport 1",
"BT Sport 2",
"beIN Sports 1 HD (fr)",
"beIN Sports 2 HD (fr)",
"beIN Sports 3 HD (fr)",
"Матч ТВ",
"Матч! Футбол 1",
"Матч! Футбол 2",
"Матч! Футбол 3",
"Наш Футбол",
"Конный Мир",
"Box Nation",
#Bulgarian
"БНТ 1",
"БНТ 2",
"BNT World",
"БНТ HD",
"Btv",
"Btv Comedy",
"Btv Cinema",
"Btv Action",
"Btv Lady",
"Ring",
"Nova",
"Diema",
"Diema Family",
"KinoNova",
"Nova Sport",
"Diema Sport",
"Diema Sport 2",
"Fox",
"Fox Crime",
"Fox Life",
"National Geographic",
"NatGeo Wild",
"Viasat Nature/History HD",
"Viasat Explorer",
"Viasat History",
"Viasat Nature",
##BG EPG
"24kitchen",
"359TV",
"amc",
"AXN",
"AXNBlack",
"AXNWhite",
"agroTV",
"Alfa",
"AnimalPlanet",
"AutoMotorSport",
"ActionPlus",
#"BNTWorld",
#"BNT1",
#"BNT2",
#"BNTHD",
"BulgariaOnAir",
"Bloomberg",
"BoxTV",
#"bTV",
#"bTVAction",
#"bTVComedy",
#"bTVCinema",
#"bTVLady",
"Vratza",
"VTK",
"Boomerang",
"BGMusicChannel",
"BabyTV",
"BiT",
"Balkanika",
"BulHistory",
"BrazzersTVEurope",
"CartoonNetwork",
"City",
"CNN",
"Euronews",
"ChernoMore",
"CBSReality",
"CBSDrama",
"CI",
"ComedyCentral",
"ComedyPlus",
"CinemaPlus",
#"dummy",
#"Diema",
#"DiemaFamily",
#"DiemaSport",
#"DiemaSport2",
"Discovery HD",
"Discovery",
"Discovery World",
"Discovery Science",
"DuckTV",
"Disney",
"DisneyJunior",
"DocuBox",
"DaVinciLearning",
"DSTV",
"DMSat",
"DeluxeLoungeHD",
"DestinationBG",
"Eurocom",
"tveurope",
"Ekids",
"Eurosport1",
"Eurosport2",
"EnglishClubTV",
"FolklorTV",
"FENTV",
"FenFolk",
#"FOX",
#"FOXLife",
#"FOXCrime",
"FineLiving",
"FPlus",
"FilmPlus",
"FashionTV",
"FoodNetworkHD",
"Fiesta",
"FilmBoXtraHD",
"FightBox",
"FilmBoxPlusHD",
"FixFoxy",
"History",
"HobbyTV",
"HobbyTVHD",
"HobbyLovHD",
"HustlerTV",
"HitMix",
"HMTV",
"ID",
"IDXtra",
"JimJam",
"Jukebox",
"Kanal3",
"KinoNova",
"MagicTV",
"mezzo",
"MTVRocks",
"MTVHits",
"MyZen",
"music",
"MotoSportHD",
"MedicalChannel",
"MovieSTAR",
"MTVLiveHD",
"MAD",
#"Nova",
#"NovaSport",
#"NatGeo",
#"NatGeoWild",
"NickJr",
"Nickelodeon",
"news",
"Outdoor",
"OtBlizoHD",
"PerviyKanal",
"PlanetaFolk",
"Planeta",
"PlanetaHD",
"PVTV",
"Trakiq",
"porn",
"RING",
"Rimeks",
"Ribalka",
"Rodina",
"Skat",
"SportPlusHD",
"TheVoice",
"TV1",
"Travel",
"TravelHD",
"TVT",
"TiankovFolk",
"TraceSportStars",
"TVPlus",
"TV1000",
"TravelChannel",
"TLC",
"Telekabel",
"TheWorld",
"VTV",
"VH1",
"VH1Classic",
"WorldFashionChannel",
#Russian
"Первый канал. (Европа)",
"Первый канал",
"Viasat Nature/History HD",
"ТВН - ТВ Центр",
"ТНТ",
"RTVi",
"Живи",
"Охота и рыбалка",
"Россия HD",
"НТВ",
"Россия 24",
"НТВ-Мир",
"РТВ - Наше кино",
"РТР Планета СНГ",
"Дом кино",
"Время",
"Телекафе",
"Русский Экстрим",
"ТБН",
"Наука 2.0",
"Россия 1",
"Russian Travel Guide (RTG TV)",
#"НТВ-ПЛЮС Наш Футбол",
#"Наш Футбол HD",
#"Матч ТВ",
#"МАТЧ! Футбол 1",
#"МАТЧ! Футбол 2",
#"МАТЧ! Футбол 3",
"Армения ТВ",
#"Конный Мир",
"Еврокино",
"Моя Планета",
"Ю",
"РЕН ТВ",
"Русский Иллюзион",
"TV1000 Megahit HD",
"TV1000 Premium HD",
"TV1000 Comedy HD",
"СТС",
"ICTV (Украина)",
"СТБ",
"НТН (Украина)",
"ТЕТ",
"Новый Канал",
"112 Украина",
"5 канал (Украина)",
"Тонис",
"Наука",
"Шансон-TB",
"Музыка Первого",
"MusicBox TV",
###Serbian
#"Arena Sport 1",
#"Arena Sport 2",
#"Arena Sport 3",
#"Arena Sport 4",
#"Arena Sport 5",
#"Arena Sport 1 HR",
#"Arena Sport 2 HR",
#"Arena Sport 3 HR",
#"Arena Sport 4 HR",
#"Arena Sport 5 HD (HR)",
"Motors TV UK",
"Pink Kids",
"Pink Western",
"Pink Classic",
"Pink Movies",
"Pink Romance",
"Pink Thriller",
"Pink Action",
"Pink Crime & Mystery",
"Pink Sci Fi & Fantasy",
"Pink Comedy",
"Pink Horror",
"Pink Family",
"Pink Premium",
"Pink Film",
"Pink Soap",
"Pink Serije",
"Pink World Cinema",
"Pink Show",
"Pink Style",
"Pink Extra",
"Pink World",
"Pink Reality",
"Pink Zabava",
"Pink Plus",
"Pink Fashion",
"Pink Live",
"Pink Folk 1",
"Pink Folk 2",
"Pink Hits 1",
"Pink Hits 2",
"Pink Koncert",
"Pink Parada",
"Pink&Roll",
"Pink Music 1",
"Pink Music 2",
"Pink Music 3",
"Pink Music 4",
"Pink Music 5",
"Pink Nostalgie",
"CCTV9 Documentary",
"Dorcel",
"Brazzers",
"Hustler",
"Hustler HD",
#"Sky Sports 1 UK",
#"Sky Sports 2 UK",
#"Sky Sports 3 UK",
#"Sky Sports 4 UK",
#"Sky Sports 5 UK",
#"Sky Sports F1 UK",
"Sky Hits DE",
"Sky Action DE",
"Sky Atlantic DE",
"Sky Cinema DE",
"Syfy DE",
"13th Street DE",
"TNT Film DE",
"TNT Serie DE",
"MGM DE",
#"BT Sport 1 UK",
#"BT Sport 2 UK",
#"BOX Nation UK",
"Rai 1 IT",
"Rai 2 IT",
"Sky Sport Austria DE",
"Sky Fußball Bundesliga DE",
#"Sport1 DE",
#"Sport1+ DE",
#"Sport1 US DE",
"Eurosport 1 DE",
"National Geographic DE",
"Nat Geo Wild DE",
"Discovery Channel DE",
"History Channel DE",
#"beIN Sport 1 (Fr)",
#"beIN Sport 2 (Fr)",
#"beIN Sport 3 (Fr)",
"France 24",
"Al Jazeera",
"BBC World",
"3sat DE",
"Arte DE",
#"RTL DE",
#"RTL 2 DE",
#"ProSieben DE",
#"Sat.1 DE",
"ZDF DE",
"Lig TV 1 (Tr)",
"Lig TV 2 (Tr)",
"Lig TV 3 (Tr)",
"Digi Sport 1",
"Digi Sport 2",
"Digi Sport 3",
"Canal+ Deportes (Spa) ",
#"FOX Sports 1 (Nl)",
#"FOX Sports 2 (Nl)",
#"FOX Sports 3 (Nl)",
#"FOX Sports 4 (Nl)",
#"FOX Sports 5 (Nl)",
"ORF 1",
"ORF 2",
"BBC World News",
"CI",
"Comedy Central UK",
"CNBC UK",
"Food Network",
"H2 UK",
"Sky 1 UK",
"Sky 2 UK",
"Sky Movies Action &amp; Adventure UK",
"Sky Movies Comedy UK",
"Sky Movies Sci-Fi &amp; Horror UK",
"Sky Movies Select UK",
"Sky Movies Family UK",
"Sky Movies Premiere UK",
"Sky Movies Drama &amp; Romance UK",
"Setanta Sports Ireland 1 UK",
"Premier Sports UK",
"NHK World UK",
"Racing UK",
"Sky News UK",
"Travel Channel",
"DeutscheWelle",
"KBSWorld",
"GINXTV",
"iConcerts",
"Discovery Turbo UK",
"CMusicTV",
"mezzolivehd",
"RussiaToday",
"CCTVNews",
"mad",
"DEVIVA",
"DEJukeBox",
"DEDeluxeMusic",
"DEZDFInfo",
"DEZDFKultur",
"DEZDFNeo",
"ArirangTV",
"Sci-FiTelly",
"AlienInvasion",
"FilmboxArthouseHD",
"360TuneBoxHD",
"FastnFunBoxHD",
"FashionBox",
"NTV-Public",
"NTV-Education",
"NTV-Media",
"PK-test",
"FP-test",
"Russia Today Documentary",
"PIK",
"MusicBoxTV",
"MusicBoxRU",
"MusicBoxUA",
"RUMTV",
"RusongTV",
"1HD",
"FashionOneHD",
"NHKWorld",
"E4",
"BBC1",
"CBBC",
"CBSRealityUK",
"CBSDramaUK",
"Bein Sports HD (es)",
"Bein Sports 1",
"Bein Sports 2",
"Bein Sports 3",
"Bein Sports 4",
"beIN Sport 1 (Fr)",
"beIN Sport 2 (Fr)",
"beIN Sport 3 (Fr)",
"France 2 (Fr)",
"France 3 (Fr)",
"RTL9 (Fr)",
#German
"Kabel Eins DE",
"Super RTL DE",
"ARD",
"RTL DE",
"RTL 2 DE",
"ProSieben DE",
"SAT1",
"VOX",
"Sixx DE",
"KiKA",
"Das Erste",
]
